testing code coverage job on main

diff --git a/.github/workflows/compass-manager.yaml b/.github/workflows/compass-manager.yaml
--- a/.github/workflows/compass-manager.yaml
+++ b/.github/workflows/compass-manager.yaml
@@ -24,6 +24,8 @@ on:
       - LICENSE
       - .gitignore
       - "**.md"
+    branches:
+      - main
 
 permissions:
   id-token: write # This is required for requesting the JWT token
@@ -116,42 +118,42 @@ jobs:
           coverage-file-name: "coverage.txt"
           github-baseline-workflow-ref: ${{ github.event.pull_request.head.ref }}
 
-  build-image:
-    needs: setup
-    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
-    with:
-      name: compass-manager
-      dockerfile: Dockerfile
-      context: .
-      tags: ${{ needs.setup.outputs.tag }}
-
-  summary:
-    runs-on: ubuntu-latest
-    needs: [build-image, unit-tests]
-    if: success() || failure()
-    steps:
-      - name: "Download test log"
-        uses: actions/download-artifact@v4
-        continue-on-error: true
-        with:
-          name: ${{ env.unit-test-log }}
-      - name: "Generate summary"
-        run: |
-          {
-            echo '# Compass Manager'
-            # if test log exists
-            if [ -f ${{ env.unit-test-log }} ]; then
-              echo '## Unit Tests'
-              printf '\n<details>\n<summary>click to expand logs</summary>\n'
-              printf '\n```\n'
-              cat ${{ env.unit-test-log }}
-              printf '\n```\n</details>\n'
-            fi
-            # if build-image was successful
-            if [ "${{ needs.build-image.result }}" == "success" ]; then
-              printf '\n\n## Image\n'
-              printf '\n```json\n'
-              echo '${{ needs.build-image.outputs.images }}' | jq
-              printf '\n```\n'
-            fi
-          } >> $GITHUB_STEP_SUMMARY
+#  build-image:
+#    needs: setup
+#    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
+#    with:
+#      name: compass-manager
+#      dockerfile: Dockerfile
+#      context: .
+#      tags: ${{ needs.setup.outputs.tag }}
+#
+#  summary:
+#    runs-on: ubuntu-latest
+#    needs: [build-image, unit-tests]
+#    if: success() || failure()
+#    steps:
+#      - name: "Download test log"
+#        uses: actions/download-artifact@v4
+#        continue-on-error: true
+#        with:
+#          name: ${{ env.unit-test-log }}
+#      - name: "Generate summary"
+#        run: |
+#          {
+#            echo '# Compass Manager'
+#            # if test log exists
+#            if [ -f ${{ env.unit-test-log }} ]; then
+#              echo '## Unit Tests'
+#              printf '\n<details>\n<summary>click to expand logs</summary>\n'
+#              printf '\n```\n'
+#              cat ${{ env.unit-test-log }}
+#              printf '\n```\n</details>\n'
+#            fi
+#            # if build-image was successful
+#            if [ "${{ needs.build-image.result }}" == "success" ]; then
+#              printf '\n\n## Image\n'
+#              printf '\n```json\n'
+#              echo '${{ needs.build-image.outputs.images }}' | jq
+#              printf '\n```\n'
+#            fi
+#          } >> $GITHUB_STEP_SUMMARY
